# Generated by Django 5.2 on 2026-02-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('travel_class', models.CharField(blank=True, choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd')], max_length=10)),
                ('port_of_embarkation', models.CharField(blank=True, choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=10)),
                ('cabin', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
