# Generated by Django 5.2 on 2026-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('master', 'Master'), ('miss', 'Miss')], max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('travel_class', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('is_alone', models.BooleanField(default=False)),
                ('with_parents', models.BooleanField(default=False)),
                ('parents_count', models.IntegerField(default=0)),
                ('with_spouse', models.BooleanField(default=False)),
                ('spouse_count', models.IntegerField(default=0)),
                ('with_children', models.BooleanField(default=False)),
                ('children_count', models.IntegerField(default=0)),
                ('with_siblings', models.BooleanField(default=False)),
                ('siblings_count', models.IntegerField(default=0)),
            ],
        ),
    ]
